name: MagicTorches
main: sorklin.magictorches.MagicTorches
version: 0.22
author: Sorklin
description: MagicTorches creates linked array of wireless torches.
commands:
  mt:
    description: Information and commands regarding magicbuttons.
    aliases: [magictorch, magictorches]
    usage: |
           /<command> <parameter> [optional arguments]
           Type "/mt help" for more information.
permissions:
  magictorches.*:
    description: Gives access to all MT commands
    children:
      magictorches.create: true
      magictorches.admin: true
  magictorches.create:
    description: Allows you to create and edit MagicTorch arrays.
    default: true
  magictorches.admin:
    description: Allows you to see and edit all MagicTorch arrays.
    default: op